<a href="https://colab.research.google.com/github/lapy113/ML-Lab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Question 1

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files
from google.colab import drive

In [ ]:
arr=np.zeros(10)
print(arr)
arr1=np.ones(10)
print(arr1)
arr2=np.ones(10)*5
print(arr2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
arr = np.array([i for i in range(10,51) if i%2==0])
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
num = np.random.uniform(0,1,1)
num

array([0.0360275])

In [ ]:
x = np.random.rand(3,4)
x
f_name = 'matrix.txt'
np.savetxt(f_name,x)
y = np.loadtxt(f_name)
print ('[+] File Loaded - ',f_name)
y

[+] File Loaded -  matrix.txt


array([[0.48302703, 0.39692429, 0.78741811, 0.72076931],
       [0.70344381, 0.01830295, 0.0866414 , 0.05295445],
       [0.65818554, 0.46210358, 0.98290954, 0.15824991]])

#2nd Question

In [ ]:
import matplotlib.image as img


image_matrix = img.imread('dog.jpg')
print(image_matrix.shape)
#convert into 2D
image_matrix = image_matrix.reshape(image_matrix.shape[0],-1)

df = pd.DataFrame(image_matrix)

print(df.tail(5))
df.to_csv('dog_csv',index = False)
rows = len(df)
print(rows)
cols = len(df.columns)

df_read = pd.read_csv('dog_csv', nrows = rows - 1, usecols = range(cols - 1))
print(df_read.tail(5))


(4160, 3120, 3)
      0     1     2     3     4     5     ...  9354  9355  9356  9357  9358  9359
4155    56    40    41    55    39    40  ...   130   136   134   128   134   132
4156    57    41    42    55    39    40  ...   122   128   126   132   138   136
4157    56    40    41    56    40    41  ...   134   140   138   133   139   137
4158    58    42    43    58    42    43  ...   143   149   147   134   140   138
4159    60    44    45    61    45    46  ...   128   134   132   139   145   143

[5 rows x 9360 columns]
4160
       0   1   2   3   4   5   6  ...  9352  9353  9354  9355  9356  9357  9358
4154  55  39  40  54  38  39  55  ...   150   148   147   153   151   145   151
4155  56  40  41  55  39  40  55  ...   134   132   130   136   134   128   134
4156  57  41  42  55  39  40  56  ...   127   125   122   128   126   132   138
4157  56  40  41  56  40  41  57  ...   135   133   134   140   138   133   139
4158  58  42  43  58  42  43  60  ...   147   145   143   149 

In [ ]:
from datetime import date
today = pd.to_datetime(date.today()).date()
print(today)

2021-08-10


# 3rd Question

In [ ]:
year=int(input("year:"))
print()
month=int(input("month:"))
print()
day=int(input("day:"))

dob = date(year,month,day)

today = date.today()
age = today.year - dob.year - ((today.month,today.day)<(dob.month,dob.day))
print("your age is : ",age)

year:2000

month:4

day:23
your age is :  21
